import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";
import { Header, Footer, Sidebar } from "@/components";

export const metadata: Metadata = {
  title: "MyTop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <main className={styles.body}>{children}</main>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
