import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "MyTop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("%с LAYOUT", "background: red");

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.nav}>
          <ul>
            <li>Курси</li>
            <li>Для дітей</li>
            <li>про нас</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
