import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSansBold = localFont({
  src: "./fonts/OpenSans-Bold.ttf",
  variable: "--font-geist-sans-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MyTop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSansBold.variable} ${geistSansBold.variable}`}>
        {children}
      </body>
    </html>
  );
}
