import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";
import { Header, Footer, Sidebar } from "@/components";
// import { AppContextProvider } from "@/context/app.context";
// import { getMenu } from "@/api/menu";

export const metadata: Metadata = {
  title: "MyTop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { menu } = await getMenu(0);
  // console.log(data);

  return (
    <html lang="en">
      <body>
        {/* <AppContextProvider menu={menu}> */}
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <main className={styles.body}>{children}</main>
          <Footer className={styles.footer} />
        </div>
        {/* </AppContextProvider> */}
      </body>
    </html>
  );
}
